name: isort
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: python-isort
        uses: isort/isort-action@v1
        with:
          requirements-files: "requirements.txt"
      
